### ISSUE TITLE
CSSMinifier does not support some CSS

### ISSUE THREAD

**Issue by jebadero** [logicsquad/minifier#2]
Hi Paul,

I was looking for a integrated CSS and JS minifier for our java/wo apps.
We tried yours but some CSS rules are not supported.
I found a hack for the first ones (classes starting with hacked-) but for the other ones using multiple ( ), I did not find any hack.
Do you think you could make your minifier work for them ?

```
.hacked-var {
    color: var(--vert)
}

.hacked-content:before {
    content: "Quantité x"
}

.hacked-important {
     width: 50% !important
}

.background-linear {
    background: linear-gradient(0deg, rgba(152, 152, 139, 0.468207351299895) 0%, rgba(255, 255, 255, 0) 100%);
}

.grid-template {
    grid-template-columns: repeat(5, minmax(15%, 1fr));
}

.calc {
    top: calc((40px - 1.75rem) / 2);
}

.svg { 
    background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'><g stroke='var(--vert)'><path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z'/><path d='m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z'/></g></svg>") center center no-repeat; background-color: transparent;
}
```
    
and the hack is 

```
Reader input = new StringReader(new String(_fileBytes)
	.replace("!important", "!important;")
	.replace("! important", "!important;")
	.replace("\" ", "\"; ")
	.replace("\"\n", "\";\n")
	.replace(")", ");")
	.replace(";;", ";"));
Writer output = new FileWriter(fileOutIn);
Minifier min = new CSSMinifier(input);
min.minify(output);
```

Have a nice day

**Comment by paulhoadley** [comment]
Hi Jérémy,

Thanks for the feedback! The short answer is that this project just pulls together two _existing_ minification algorithms from different projects that I thought were reasonably conservative. CSS is minified by code from the [CSSMin](https://github.com/barryvan/CSSMin) project. It's unlikely I made any significant changes to the approach. If you take a look at that project, its last commit was 2017, so any syntax additions since then are not going to be supported, and might even be unintentionally mangled—not sure if that's what is happening here, just pointing out the timeline.

In any case, I'll take a look at your examples at some point. If you want to supply your suggested workaround there as a pull request, I could look at that as well.

**Comment by paulhoadley** [comment]
I've reproduced and fixed the issue in the first three examples: basically, there was over-eager truncation of the end of a property's content if it was the last in a block and omitted the trailing semi-colon. Easily fixed.

I'm not sure I see the issue with the remaining examples. These produce:

```
.background-linear{background:linear-gradient(0deg,rgba(152,152,139,0.468207351299895) 0,rgba(255,255,255,0) 100%)}

.grid-template{grid-template-columns:repeat(5,minmax(15%,1fr))}

.calc{top:calc((40px - 1.75rem) / 2)}

.svg{background:url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'><g stroke='var(--vert)'><path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z'/><path d='m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z'/></g></svg>") center center no-repeat; background-color: transparent}
```

Can you point me to the issue(s) with these?

**Comment by paulhoadley** [comment]
I'm reasonably sure this is working fine for the remaining test cases supplied above. I've added them to the test examples for `CSSMinifierTest`. Let me know if there remains some problem with them.
