### ISSUE TITLE
minifier incorrectly flags some proper comments as "unterminated"

### ISSUE THREAD

**Issue by GregorySokoloff** [logicsquad/minifier#4]
This legal css comment:

/************************* general stuff **********/

triggers an unterminated comment exception. I'm guessing it has something to do with "special comments", whatever they are.

Cheers

**Comment by GregorySokoloff** [comment]
I spoke too fast! Now I can't reproduce the problem easily, even though the removal of the offending line fixed the problem before. Argh!

**Comment by GregorySokoloff** [comment]
Ahhh...now I can reproduce the problem with this valid comment followed immediately by the universal selector:

/**/* {box-sizing: border-box;}

The confusion is that the termination of the ignored "special comment" is immediately followed by the universal selector and that is interpreted incorrectly as the start of a new comment.

Cheers

**Comment by paulhoadley** [comment]
Thanks for the report. I'll take a look at some point.

**Comment by paulhoadley** [comment]
I think what's going on here is that our code ported from [CSSMin](https://github.com/barryvan/CSSMin) is trying to _preserve_ "Javadoc-style" comments:

```
	while ((n = sb.indexOf("/*", n)) != -1) {
		if (sb.charAt(n + 2) == '*') { // Retain special comments
			n += 2;
			continue;
		}
```

(I note that it doesn't seem to be documented other that by that inline comment above, but that certainly seems to be the effect.) After we've skipped `/**` in your sample input, then there is, indeed, no comment terminator in the remaining input. The fix will be to see if the _very next_ character is `/`, in which case we've got the unusual input above, `/**/`, _not_ a "Javadoc-style" comment.
