### ISSUE TITLE
grid-template-column and -row parameters are simplified, but they are significant

### ISSUE THREAD

**Issue by ericschaefer** [logicsquad/minifier#7]
All parameters for grid-template-columns and grid-template-rows are significant even when identical.
i.e. `grid-template-columns: 1fr 1fr` can't be simplified to `grid-template-columns: 1fr`.

see https://github.com/logicsquad/minifier/pull/6 for fix

**Comment by ericschaefer** [comment]
Is there anything I can do to move this issue/PR forward?

**Comment by paulhoadley** [comment]
Hi Eric,

Sorry, I completely missed this. I'll take a look next week.

**Comment by paulhoadley** [comment]
Merged. Thanks @ericschaefer. Sorry about the delay. There's no real timeline for a 1.3 release: do you want/need this to go out in a release?

**Comment by ericschaefer** [comment]
A release would be really great, if it isn't too much effort.

**Comment by paulhoadley** [comment]
Will do.
