### ISSUE TITLE
Broken template literals

### ISSUE THREAD

**Issue by porkotron** [logicsquad/minifier#8]
Minifying this js:
```
tagFunction`string text ${expression} string text`
```
Outputs:
```
tagFunction`string text ${expression}string text`
```
Backticks are used as delimiters in [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by paulhoadley** [comment]
Thanks for this, and PR #9. I will take a look at it soon.
